version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeper
    expose:
      - 2181

  kafka:
    image: wurstmeister/kafka:0.10.2.1
    container_name: kafka
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  accelerator:
    image: manvel7650/microservices-workshop-accelerator:latest
    container_name: accelerator
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - PROFILE=
      - JAVA_OPTS=
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - ACCELERATOR_COLLISION_INTERVAL=5000
    depends_on:
      - kafka

  cqrs:
    image: manvel7650/microservices-workshop-cqrs:latest
    container_name: cqrs
    expose:
      - 8080
    ports:
      - "8081:8080"
    environment:
      - PROFILE=
      - JAVA_OPTS=
      - API_HREF=http://localhost:8081/api
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    depends_on:
      - kafka