version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeper
    expose:
      - 2181

  kafka:
    image: wurstmeister/kafka:0.10.2.1
    container_name: kafka
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  accelerator:
    image: manvel7650/microservices-workshop-accelerator:latest
    container_name: accelerator
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - PROFILE=local
    depends_on:
      - kafka

  registry:
    image: manvel7650/microservices-workshop-registry:latest
    container_name: registry
    expose:
      - 8080
    ports:
      - "8090:8080"
    environment:
      - PROFILE=
      - JAVA_OPTS=

  gateway:
    image: manvel7650/microservices-workshop-gateway:latest
    container_name: gateway
    expose:
      - 8080
    ports:
      - "8091:8080"
    environment:
      - PROFILE=
      - JAVA_OPTS=
    depends_on:
      - registry

  write-model:
    image: manvel7650/microservices-workshop-write-model:latest
    container_name: write-model
    expose:
      - 5005
    ports:
      - "5005:5005"
    environment:
      - PROFILE=
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    depends_on:
      - kafka

  collision-read-model:
    image: manvel7650/microservices-workshop-collision-read-model:latest
    container_name: collision-read-model
    expose:
      - 8080
      - 5005
    ports:
      - "8081:8080"
      - "5006:5005"
    environment:
      - PROFILE=
      - JAVA_OPTS=-Ddetector.name=lousy-detector -Ddetector.apiHref=http://localhost:8091/api -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    depends_on:
      - kafka
      - gateway