version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeper
    expose:
      - 2181

  kafka:
    image: wurstmeister/kafka:0.10.2.1
    container_name: kafka
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  accelerator:
    image: manvel7650/microservices-workshop-accelerator:latest
    container_name: accelerator
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - PROFILE=
      - JAVA_OPTS=
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - ACCELERATOR_COLLISION_INTERVAL=5000
    depends_on:
      - kafka

  registry:
    image: manvel7650/microservices-workshop-registry:latest
    container_name: registry
    environment:
      - PROFILE=
      - JAVA_OPTS=
      - EUREKA_CLIENT_SERVICE_URL_defaultZone=http://registry:8080/eureka

  gateway:
    image: manvel7650/microservices-workshop-gateway:latest
    container_name: gateway
    expose:
      - 8080
    ports:
      - "8081:8080"
    environment:
      - PROFILE=
      - JAVA_OPTS=
      - EUREKA_CLIENT_SERVICE_URL_defaultZone=http://registry:8080/eureka
    depends_on:
      - registry

  particle-detector:
    image: manvel7650/microservices-workshop-particle-detector:latest
    container_name: particle-detector
    environment:
      - PROFILE=
      - JAVA_OPTS=
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - KAFKA_GROUP=particle-detector
    depends_on:
      - kafka

  collision-detector:
    image: manvel7650/microservices-workshop-collision-detector:latest
    container_name: collision-detector
    environment:
      - PROFILE=
      - JAVA_OPTS=
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - KAFKA_GROUP=collision-detector
    depends_on:
      - kafka

  collision-read-model:
    image: manvel7650/microservices-workshop-collision-read-model:latest
    container_name: collision-read-model
    environment:
      - PROFILE=
      - JAVA_OPTS=
      - API_HREF=http://localhost:8081/collisions/api
      - API_MODE=collisions
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - EUREKA_CLIENT_SERVICE_URL_defaultZone=http://registry:8080/eureka
      - KAFKA_GROUP=collision-read-model
    depends_on:
      - kafka
      - gateway

  collision-read-model-2:
    image: manvel7650/microservices-workshop-collision-read-model:latest
    container_name: collision-read-model-2
    environment:
      - PROFILE=
      - JAVA_OPTS=
      - API_HREF=http://localhost:8081/collisions/api
      - API_MODE=collisions
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - EUREKA_CLIENT_SERVICE_URL_defaultZone=http://registry:8080/eureka
      - KAFKA_GROUP=collision-read-model-2
    depends_on:
      - kafka
      - gateway

  statistics-read-model:
    image: manvel7650/microservices-workshop-statistics-read-model:latest
    container_name: statistics-read-model
    environment:
      - PROFILE=
      - JAVA_OPTS=
      - API_HREF=http://localhost:8081/statistics/api
      - API_MODE=statistics
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - EUREKA_CLIENT_SERVICE_URL_defaultZone=http://registry:8080/eureka
      - KAFKA_GROUP=statistics-read-model
    depends_on:
      - kafka
      - gateway
