detector:
# TODO 1. Enter a UNIQUE name for your detector here
#  name: MyAwesomeDetector
  apiHref: http://localhost:8080

spring:
# TODO 2. Configure spring streams to connect to kafka
#  cloud:
#    stream:
#      bindings:
#        accelerator_input:
#          binder: kafka
#          destination: accelerator
#      kafka:
#        binder:
#          headers:
#            - AGGREGATE
#            - EVENT_TYPE
#          brokers: kafka
#          defaultBrokerPort: 9092
#          zkNodes: zookeeper
#          defaultZkPort: 2181