spring:
  application:
    name: gateway

zuul:
  routes:
    collisions:
      path: /collisions/**
      serviceId: collision-read-model
    statistics:
      path: /statistics/**
      serviceId: statistics-read-model